// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConstants():Promise<main.AppConstants>;

export function GetWalkDir():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenMarkdown(arg1:string):Promise<void>;

export function OpenWorkspace(arg1:string):Promise<void>;

export function RemoveMarkdown(arg1:string):Promise<void>;

export function RenameMarkdown(arg1:string,arg2:string):Promise<void>;

export function SaveEdges(arg1:string):Promise<void>;

export function SaveMarkdown(arg1:string,arg2:string):Promise<void>;

export function SaveNodes(arg1:string):Promise<void>;

export function SaveToAssets(arg1:string):Promise<string>;
