// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConstants() {
  return window['go']['main']['App']['GetConstants']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenMarkdown(arg1) {
  return window['go']['main']['App']['OpenMarkdown'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function RemoveNodeLabel(arg1) {
  return window['go']['main']['App']['RemoveNodeLabel'](arg1);
}

export function RenameNodeLabel(arg1, arg2) {
  return window['go']['main']['App']['RenameNodeLabel'](arg1, arg2);
}

export function SaveEdges(arg1) {
  return window['go']['main']['App']['SaveEdges'](arg1);
}

export function SaveNodes(arg1) {
  return window['go']['main']['App']['SaveNodes'](arg1);
}

export function SaveToAssets(arg1) {
  return window['go']['main']['App']['SaveToAssets'](arg1);
}
