// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConstants() {
  return window['go']['main']['App']['GetConstants']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function SaveEdges(arg1) {
  return window['go']['main']['App']['SaveEdges'](arg1);
}

export function SaveNodes(arg1) {
  return window['go']['main']['App']['SaveNodes'](arg1);
}
